#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

if (in_array('dev_token',$_SERVER['argv']) || in_array('test_token',$_SERVER['argv'])) {
    $envStr = 'dev';
    $debugBool = true;
}elseif (in_array('prod_token',$_SERVER['argv'])) {
    $envStr = 'prod';
    $debugBool = false;
}else{
    exit('请联系管理员添加运行新参数');
}


defined('YII_DEBUG') or define('YII_DEBUG', $debugBool);
defined('YII_ENV') or define('YII_ENV', $envStr);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
